Repository googleapis/python-datalabeling, pull requests merged in 2021-04, with the labels that each got.

#85 chore: start tracking obsolete files
  synth.metadata
Labels: api: datalabeling, cla: yes, context: full

#86 chore: Add license headers for python config files
  .pre-commit-config.yaml
  docs/conf.py
  synth.metadata
Labels: api: datalabeling, automerge, cla: yes, context: full

#89 chore: prevent normalization of semver versioning
  setup.py
Labels: api: datalabeling, cla: yes

#90 chore(revert): revert preventing normalization
  setup.py
Labels: api: datalabeling, automerge, cla: yes
